/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BusinessDtoApiResponse } from '../models';
// @ts-ignore
import type { BusinessEditDto } from '../models';
// @ts-ignore
import type { BusinessesResponseDtoApiResponse } from '../models';
// @ts-ignore
import type { EmptyDtoApiResponse } from '../models';
/**
 * BusinessesApi - axios parameter creator
 * @export
 */
export const BusinessesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new business for the authenticated user
         * @param {BusinessEditDto} [businessEditDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBusiness: async (businessEditDto?: BusinessEditDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Businesses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(businessEditDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a business by ID for the authenticated user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBusiness: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteBusiness', 'id', id)
            const localVarPath = `/api/Businesses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a business by ID for the authenticated user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBusiness: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getBusiness', 'id', id)
            const localVarPath = `/api/Businesses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get all businesses for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBusinesses: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Businesses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a business by ID for the authenticated user
         * @param {string} id 
         * @param {BusinessEditDto} [businessEditDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBusiness: async (id: string, businessEditDto?: BusinessEditDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateBusiness', 'id', id)
            const localVarPath = `/api/Businesses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(businessEditDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BusinessesApi - functional programming interface
 * @export
 */
export const BusinessesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BusinessesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new business for the authenticated user
         * @param {BusinessEditDto} [businessEditDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createBusiness(businessEditDto?: BusinessEditDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BusinessDtoApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createBusiness(businessEditDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BusinessesApi.createBusiness']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a business by ID for the authenticated user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBusiness(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmptyDtoApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteBusiness(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BusinessesApi.deleteBusiness']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a business by ID for the authenticated user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBusiness(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BusinessDtoApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBusiness(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BusinessesApi.getBusiness']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get all businesses for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBusinesses(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BusinessesResponseDtoApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBusinesses(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BusinessesApi.getBusinesses']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a business by ID for the authenticated user
         * @param {string} id 
         * @param {BusinessEditDto} [businessEditDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateBusiness(id: string, businessEditDto?: BusinessEditDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BusinessDtoApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateBusiness(id, businessEditDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BusinessesApi.updateBusiness']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BusinessesApi - factory interface
 * @export
 */
export const BusinessesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BusinessesApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new business for the authenticated user
         * @param {BusinessEditDto} [businessEditDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBusiness(businessEditDto?: BusinessEditDto, options?: RawAxiosRequestConfig): AxiosPromise<BusinessDtoApiResponse> {
            return localVarFp.createBusiness(businessEditDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a business by ID for the authenticated user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBusiness(id: string, options?: RawAxiosRequestConfig): AxiosPromise<EmptyDtoApiResponse> {
            return localVarFp.deleteBusiness(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a business by ID for the authenticated user
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBusiness(id: string, options?: RawAxiosRequestConfig): AxiosPromise<BusinessDtoApiResponse> {
            return localVarFp.getBusiness(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get all businesses for the authenticated user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBusinesses(options?: RawAxiosRequestConfig): AxiosPromise<BusinessesResponseDtoApiResponse> {
            return localVarFp.getBusinesses(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a business by ID for the authenticated user
         * @param {string} id 
         * @param {BusinessEditDto} [businessEditDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBusiness(id: string, businessEditDto?: BusinessEditDto, options?: RawAxiosRequestConfig): AxiosPromise<BusinessDtoApiResponse> {
            return localVarFp.updateBusiness(id, businessEditDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BusinessesApi - object-oriented interface
 * @export
 * @class BusinessesApi
 * @extends {BaseAPI}
 */
export class BusinessesApi extends BaseAPI {
    /**
     * 
     * @summary Create a new business for the authenticated user
     * @param {BusinessEditDto} [businessEditDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessesApi
     */
    public createBusiness(businessEditDto?: BusinessEditDto, options?: RawAxiosRequestConfig) {
        return BusinessesApiFp(this.configuration).createBusiness(businessEditDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a business by ID for the authenticated user
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessesApi
     */
    public deleteBusiness(id: string, options?: RawAxiosRequestConfig) {
        return BusinessesApiFp(this.configuration).deleteBusiness(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a business by ID for the authenticated user
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessesApi
     */
    public getBusiness(id: string, options?: RawAxiosRequestConfig) {
        return BusinessesApiFp(this.configuration).getBusiness(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get all businesses for the authenticated user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessesApi
     */
    public getBusinesses(options?: RawAxiosRequestConfig) {
        return BusinessesApiFp(this.configuration).getBusinesses(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a business by ID for the authenticated user
     * @param {string} id 
     * @param {BusinessEditDto} [businessEditDto] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BusinessesApi
     */
    public updateBusiness(id: string, businessEditDto?: BusinessEditDto, options?: RawAxiosRequestConfig) {
        return BusinessesApiFp(this.configuration).updateBusiness(id, businessEditDto, options).then((request) => request(this.axios, this.basePath));
    }
}

