version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: invoiceez
      POSTGRES_PASSWORD: testing1234
      POSTGRES_DB: invoiceez
    ports:
      - "5432:5432"
    volumes:
      - postgres_invoiceez:/var/lib/postgresql/data

volumes:
  postgres_invoiceez: