/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ApiResponseCode = {
    Ok: 'Ok',
    ValidationError: 'ValidationError',
    NotFound: 'NotFound',
    Unauthorized: 'Unauthorized',
    Forbidden: 'Forbidden',
    ServerError: 'ServerError',
    BadRequest: 'BadRequest'
} as const;

export type ApiResponseCode = typeof ApiResponseCode[keyof typeof ApiResponseCode];



