/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthRefreshRequestDto
 */
export interface AuthRefreshRequestDto {
    /**
     * 
     * @type {string}
     * @memberof AuthRefreshRequestDto
     */
    'refreshToken'?: string | null;
}

