/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthRegisterRequestDto
 */
export interface AuthRegisterRequestDto {
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequestDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequestDto
     */
    'password'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequestDto
     */
    'confirmPassword': string;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequestDto
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterRequestDto
     */
    'lastName'?: string | null;
}

