/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CurrencyCode } from './currency-code';

/**
 * 
 * @export
 * @interface BusinessDto
 */
export interface BusinessDto {
    /**
     * 
     * @type {string}
     * @memberof BusinessDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof BusinessDto
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessDto
     */
    'tagline'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessDto
     */
    'address': string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessDto
     */
    'phone': string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessDto
     */
    'email': string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessDto
     */
    'website'?: string | null;
    /**
     * 
     * @type {CurrencyCode}
     * @memberof BusinessDto
     */
    'defaultCurrency'?: CurrencyCode;
    /**
     * 
     * @type {string}
     * @memberof BusinessDto
     */
    'defaultPaymentInstructions'?: string | null;
}



