/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const CurrencyCode = {
    Zar: 'ZAR',
    Usd: 'USD',
    Eur: 'EUR'
} as const;

export type CurrencyCode = typeof CurrencyCode[keyof typeof CurrencyCode];



