/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerEditDto
 */
export interface CustomerEditDto {
    /**
     * 
     * @type {string}
     * @memberof CustomerEditDto
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerEditDto
     */
    'name': string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerEditDto
     */
    'email': string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerEditDto
     */
    'phone': string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomerEditDto
     */
    'address': string | null;
}

