/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApiResponseCode } from './api-response-code';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceSummaryDto } from './invoice-summary-dto';

/**
 * 
 * @export
 * @interface InvoiceSummaryDtoApiResponse
 */
export interface InvoiceSummaryDtoApiResponse {
    /**
     * 
     * @type {ApiResponseCode}
     * @memberof InvoiceSummaryDtoApiResponse
     */
    'code'?: ApiResponseCode;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDtoApiResponse
     */
    'message'?: string | null;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof InvoiceSummaryDtoApiResponse
     */
    'formErrors'?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {InvoiceSummaryDto}
     * @memberof InvoiceSummaryDtoApiResponse
     */
    'data'?: InvoiceSummaryDto;
}



