/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CurrencyCode } from './currency-code';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoicePaymentStatus } from './invoice-payment-status';

/**
 * 
 * @export
 * @interface InvoiceSummaryDto
 */
export interface InvoiceSummaryDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'invoiceNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'invoiceDate'?: string;
    /**
     * 
     * @type {InvoicePaymentStatus}
     * @memberof InvoiceSummaryDto
     */
    'paymentStatus'?: InvoicePaymentStatus;
    /**
     * 
     * @type {number}
     * @memberof InvoiceSummaryDto
     */
    'totalAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof InvoiceSummaryDto
     */
    'itemCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof InvoiceSummaryDto
     */
    'discountCount'?: number;
    /**
     * 
     * @type {CurrencyCode}
     * @memberof InvoiceSummaryDto
     */
    'currency'?: CurrencyCode;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'customerName': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'businessId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'businessName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'createdAtUtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceSummaryDto
     */
    'modifiedAtUtc'?: string;
}



