/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InvoiceItemDto
 */
export interface InvoiceItemDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceItemDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceItemDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InvoiceItemDto
     */
    'quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof InvoiceItemDto
     */
    'rate'?: number;
    /**
     * 
     * @type {string}
     * @memberof InvoiceItemDto
     */
    'invoiceId'?: string;
}

