/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CurrencyCode } from './currency-code';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceDiscountDto } from './invoice-discount-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceItemDto } from './invoice-item-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoicePaymentStatus } from './invoice-payment-status';

/**
 * 
 * @export
 * @interface InvoiceDetailDto
 */
export interface InvoiceDetailDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'invoiceNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'invoiceDate'?: string;
    /**
     * 
     * @type {InvoicePaymentStatus}
     * @memberof InvoiceDetailDto
     */
    'paymentStatus'?: InvoicePaymentStatus;
    /**
     * 
     * @type {number}
     * @memberof InvoiceDetailDto
     */
    'totalAmount'?: number;
    /**
     * 
     * @type {CurrencyCode}
     * @memberof InvoiceDetailDto
     */
    'currency'?: CurrencyCode;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'paymentInstructions'?: string | null;
    /**
     * 
     * @type {Array<InvoiceItemDto>}
     * @memberof InvoiceDetailDto
     */
    'items'?: Array<InvoiceItemDto> | null;
    /**
     * 
     * @type {Array<InvoiceDiscountDto>}
     * @memberof InvoiceDetailDto
     */
    'discounts'?: Array<InvoiceDiscountDto> | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'businessId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'businessName': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'businessTagline'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'businessAddress': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'businessEmail': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'businessPhone': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'businessWebsite'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'customerName': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'customerAddress': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'customerEmail': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'customerPhone': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'createdAtUtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDetailDto
     */
    'modifiedAtUtc'?: string;
}



