/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceDiscountType } from './invoice-discount-type';

/**
 * 
 * @export
 * @interface InvoiceDiscountEditDto
 */
export interface InvoiceDiscountEditDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceDiscountEditDto
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDiscountEditDto
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof InvoiceDiscountEditDto
     */
    'amount'?: number;
    /**
     * 
     * @type {InvoiceDiscountType}
     * @memberof InvoiceDiscountEditDto
     */
    'type'?: InvoiceDiscountType;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDiscountEditDto
     */
    'invoiceId'?: string | null;
}



