/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CurrencyCode } from './currency-code';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceDiscountEditDto } from './invoice-discount-edit-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoiceItemEditDto } from './invoice-item-edit-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { InvoicePaymentStatus } from './invoice-payment-status';

/**
 * 
 * @export
 * @interface InvoiceEditDto
 */
export interface InvoiceEditDto {
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'invoiceNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'invoiceDate'?: string;
    /**
     * 
     * @type {InvoicePaymentStatus}
     * @memberof InvoiceEditDto
     */
    'paymentStatus'?: InvoicePaymentStatus;
    /**
     * 
     * @type {number}
     * @memberof InvoiceEditDto
     */
    'totalAmount'?: number;
    /**
     * 
     * @type {Array<InvoiceItemEditDto>}
     * @memberof InvoiceEditDto
     */
    'items'?: Array<InvoiceItemEditDto> | null;
    /**
     * 
     * @type {Array<InvoiceDiscountEditDto>}
     * @memberof InvoiceEditDto
     */
    'discounts'?: Array<InvoiceDiscountEditDto> | null;
    /**
     * 
     * @type {CurrencyCode}
     * @memberof InvoiceEditDto
     */
    'currency'?: CurrencyCode;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'paymentInstructions'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'businessId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'businessName': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'businessTagline'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'businessAddress': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'businessEmail': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'businessPhone': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'businessWebsite'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InvoiceEditDto
     */
    'shouldSaveBusiness'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'customerId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'customerName': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'customerAddress': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'customerEmail': string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEditDto
     */
    'customerPhone': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof InvoiceEditDto
     */
    'shouldSaveCustomer'?: boolean;
}



