/* tslint:disable */
/* eslint-disable */
/**
 * Invoiceez Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserChangePasswordRequestDto
 */
export interface UserChangePasswordRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserChangePasswordRequestDto
     */
    'currentPassword': string;
    /**
     * 
     * @type {string}
     * @memberof UserChangePasswordRequestDto
     */
    'newPassword': string;
    /**
     * 
     * @type {string}
     * @memberof UserChangePasswordRequestDto
     */
    'confirmNewPassword': string;
}

